### PR TITLE
Update policy.md (m211488 grammar fixes)

### PR DESCRIPTION
**Pull request by m211488**
4 grammar fixes. MIDN Dias / 211488 / Missler 5002

### CODE REVIEW

**Comment by adamaviv** [comment]
I'm not sure that these are typos in the same sense of typos ...

**Comment by m211488** [comment]
Good evening sir,

No worries sir. This change is more of a grammar correction that a typical
typo, so I'll keep searching. Have a good night!

Very Respectfully,
Thomas Dias
MIDN      USN

**Comment by adamaviv** [comment]
Let's say 1 typo ... but, it's not substantive. Sorry.

**Comment by m211488** [comment]
I apologize sir. Thank you!

Very Respectfully,
Thomas Dias
MIDN      USN

**Pull request merged**
